### ISSUE TITLE
My voice is not recorded, but my microphone is fine

### ISSUE THREAD

**Issue by kanseaveg** [e-johnstonn/wingmanAI#4]
The environment I installed is absolutely correct
![image](https://github.com/e-johnstonn/wingmanAI/assets/80022154/0402e7e9-de1c-47c5-aa6e-9bbf381e77ee)

![image](https://github.com/e-johnstonn/wingmanAI/assets/80022154/044faffb-3d5f-4354-83b3-6c7005ff1f10)

I tried to test my default microphone device on a microphone testing website, and I can see that it is normal and there are noises
![image](https://github.com/e-johnstonn/wingmanAI/assets/80022154/b6b05f8d-7d0f-458f-87f1-9693619e5fb3)

But the program does not seem to collect my voice, how to solve it

**Comment by e-johnstonn** [comment]
Could you show the full error message you're getting? Is the issue that when you talk, the program crashes?

**Comment by kanseaveg** [comment]
My program's error log output is:
```
C:\Users\tarob\anaconda3\envs\pytorch\python.exe D:\project\whisper\wingmanAI\main.py 
C:\Users\tarob\anaconda3\envs\pytorch\lib\site-packages\whisper\timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker...
[INFO] Completed ambient noise adjustment for Default Speaker.
Whisper running on device: cuda:0
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\tarob\anaconda3\envs\pytorch\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\tarob\anaconda3\envs\pytorch\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "D:\project\whisper\wingmanAI\AudioTranscriber.py", line 52, in transcribe_audio_queue
    text = self.get_transcription(temp_file)
  File "D:\project\whisper\wingmanAI\AudioTranscriber.py", line 89, in get_transcription
    result = self.audio_model.transcribe(file_path, fp16=torch.cuda.is_available())
  File "C:\Users\tarob\anaconda3\envs\pytorch\lib\site-packages\whisper\transcribe.py", line 121, in transcribe
    mel = log_mel_spectrogram(audio, padding=N_SAMPLES)
  File "C:\Users\tarob\anaconda3\envs\pytorch\lib\site-packages\whisper\audio.py", line 130, in log_mel_spectrogram
    audio = load_audio(audio)
  File "C:\Users\tarob\anaconda3\envs\pytorch\lib\site-packages\whisper\audio.py", line 46, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\Users\tarob\anaconda3\envs\pytorch\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "C:\Users\tarob\anaconda3\envs\pytorch\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\tarob\anaconda3\envs\pytorch\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\tarob\anaconda3\envs\pytorch\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 

```
please help me to solve this problem. thank you.

**Comment by e-johnstonn** [comment]
It looks like you don’t have ffmpeg installed. Try running 

```conda install -c conda-forge ffmpeg```

in your anaconda prompt/command prompt.
